version: "2.0"
services:
  fastapi_app:
    container_name: fastapi_app
    build:
      context: .
    ports:
      - "5000:5000"

networks:
  default:
    name: fastapi_app_network
    driver: bridge
